if [ -n "$(echo $SSH_CONNECTION)" ]; then
	ssh_status="(ssh|$(hostname)) "
else
	ssh_status=""
fi
PS1='\[\033[01;32m\]${ssh_status}\D{%a %d.%m}\[\033[01;34m\]|\[\033[01;32m\]\A\[\033[01;34m\]|\[\033[01;32m\]${PWD#"${PWD%/*/*}/"}\[\033[00m\]\$ '
export LANG=en_IN.UTF-8
				

