#! /bin/bash

mkdir -p ~/.config
for value in nvim 
do
    echo "Linked ${value} config"
   cp -al dotfiles/.config/$value ~/.config > /dev/null 2>&1
done

ln -f dotfiles/tmux.conf ~/.tmux.conf
echo "Linked tmux.conf"

ln -f dotfiles/vimrc ~/.vimrc_haran
echo "Linked vimrc"

ln -f dotfiles/gitconfig ~/.gitconfig
echo "Linked gitconfig"

if [[ -e ~/.zshrc ]]; then
	    ln -f dotfiles/zsh_profile ~/.zsh_profile
	    if [[ -z $(cat ~/.zshrc | grep "source ~/.zsh_profile") ]]; then
		echo "source ~/.zsh_profile" >> ~/.zshrc
	    fi
	    echo "Linked zsh_profile and configured zshrc to source it"
	    echo "Restart the terminal for changes to take effect"
else
	    ln -f dotfiles/bash_profile ~/.bsh_prof
	    if [[ -z $(cat ~/.bashrc | grep "source ~/.bsh_prof") ]]; then
		echo "source ~/.bsh_prof" >> ~/.bashrc
	    fi
	    echo "Linked bash_profile and configured bashrc to source it"
	    echo "Restart the terminal for changes to take effect"
fi

if [ $(uname -s) = "Linux" ]; then
    echo "Detected linux"
    #mkdir -p ~/.dir_colors/dircolors
    #ln -f  dotfiles/dircolors ~/.dir_colors/dircolors
    #echo "Hard-linked dircolors"
    
    #mkdir -p ~/.config/terminator
    #ln -f  dotfiles/terminator_config ~/.config/terminator/config
    #echo "Hard-linked terminator config"
elif [ $(uname -s) = "Darwin" ]; then
    # for value in karabiner ranger sketchybar skhd yabai
    # do
    #     echo "Linked ${value} config"
    # cp -al dotfiles/.config/$value ~/.config > /dev/null 2>&1
    # done
    echo "Detected macOS"
    cp dotfiles/com.googlecode.iterm2.plist ~/Library/Preferences

    mkdir -p ~/Library/Application\ Support/MailMate/Resources/KeyBindings/ 
    ln -f dotfiles/mailmate_keybindings.plist ~/Library/Application\ Support/MailMate/Resources/KeyBindings/MyKBDs.plist
    echo "Linked MailMate config"
    cp -r dotfiles/mailmate_bundles/* ~/Library/Application\ Support/MailMate/Bundles/
    echo "Linked MailMate bundles"
else 
    echo $OSTYPE
    echo "OS not recognized"
fi
